---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: movie-frontend
  labels:
    env: frontend
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      env: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        env: frontend
    spec:
      containers:
        - name: moviefrontend-svc
          image: manoj406/movieshopfrontend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://movie-svc:8000/movie
          resources: 
            requests:
              cpu: 800m
              memory: 124Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          

---
apiVersion: v1
kind: Service
metadata: 
  name: moviefrontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    env: frontend
